// app/layout.js
import Body from "@/components/layout/Body";
import MainContextProvider from "@/context/MainContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>  {/* ← body مستقیم داخل html */}
        <MainContextProvider>
          <Body>
            {children}
          </Body>
        </MainContextProvider>
      </body>
    </html>
  );
}